### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by robbiemcmichael** [luke-clifton/json-directory#2]
It would be nice to be able to use YAML as an alternative to JSON. Are you open to adding a dependency on the [yaml](https://hackage.haskell.org/package/yaml) package and using it to decode files with extensions `.yaml` and `.yml`?

Alternatively, it might be possible to refactor this library to allow users to supply their own mapping from file extension to a function that can decode files of that type.

**Comment by luke-clifton** [comment]
I like the idea of having a `[(FilePath -> Bool, ByteString -> Either String Value)]` configuration option which would allow you to insert arbitrary parsers for a given extension, or even for specific files. The rules would be tried in order until one matched.

Current behaviour would be replicated with 

```
default =
    [ (isSuffixOf ".json", Aeson.eitherDecode)
    , (const True, Aeson.String . toS)
    ]
```

**Comment by luke-clifton** [comment]
https://github.com/luke-clifton/json-directory/pull/3

Implementation.

**Comment by luke-clifton** [comment]
Currently this requires using `IResult` for the parser. Is this going to cause problems for YAML stuff?

**Comment by luke-clifton** [comment]
Continue conversation in the PR thread.

**Comment by luke-clifton** [comment]
https://hackage.haskell.org/package/json-directory-0.1.0.1

**Comment by robbiemcmichael** [comment]
That's perfect, thanks!
